### PR TITLE
Add support for `@hubot rooms Vancouver`

### PR DESCRIPTION
**Pull request by halkeye**
@santiycr 

* Fuzzy match like the existing integration does
* Clean up eslint based fixes now that it actually runs
* clean up some dependancies
* allow mocha to be run without grunt

can you do a release after this?

### CODE REVIEW

**Comment by halkeye** [comment]
hey @santiycr do you have time to review, merge and deploy?

I'm also cool taking over ownership if you want

**Review by santiycr — APPROVED** [review]
Looks good! Thanks

**Comment by santiycr** [comment]
Sorry for the long time no answer. Been off the grid for a few weeks. Giving you ownership is next steps. Thanks for picking this project up

**Comment by santiycr** [comment]
ok, 0.1.0 release made. Also, added you as collaborator in github and npm. Thanks!

**Comment by halkeye** [comment]
The number of hubot modules on my npm page goes up again. Muahahhahahaha

**Pull request merged**
